language: php

services: mongodb

php:
  - 5.3
  - 5.4
  - 5.5
before_script:
    - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev
notifications:
  email:
    - fsemm.travis-ci@gmx.de    
